export const Selector = {
    JOB_LISTS: 'li',
    COMPANY_LINK: '.topcard__flavor--black-link',
    SEE_WHO_WAS_HIRED: 'a.face-pile__cta',
    JOB_TITLE: '.topcard__title',
    JOB_DESCRIPTION: '.description__text--rich',
    POSTED_TIME_AGO: '.posted-time-ago__text',
    SR_ONLY: 'span.sr-only',
    JOB_SEARCH_CARD: '.job-search-card',
    DATA_ENTITY_URN: 'data-entity-urn',
    EXPERIENCE_TITLE: '.description__job-criteria-subheader',
    EXPERIENCE: '.description__job-criteria-text',
    JOB_CRITERIA_ITEM: 'li.description__job-criteria-item',
    MESSAGE_THE_RECRUITER: 'div.message-the-recruiter',
    MESSAGE_THE_RECRUITER_NAME: 'h3.base-main-card__title',
    MESSAGE_THE_RECRUITER_TITLE: 'h4.base-main-card__subtitle',
    SENEORITY_LEVEL: 'li:has(h3:contains("Seniority level")) > span.description__job-criteria-text--criteria',
    MESSAGE_THE_RECRUITER_CTA: 'a.message-the-recruiter__cta',
    JOB_CRITERIA_LIST: '.description__job-criteria-list',
    JOB_CRITERIA_SUB_HEADER: '.description__job-criteria-subheader',
    JOB_CRITERIA_TEXT: '.description__job-criteria-text--criteria',
    JOB_LOCATION: '.topcard__flavor.topcard__flavor--bullet',
};
